version: '3.8'

services:
  backend:
#    image: golang:1.2
    ports:
      - "8080:8080"
    environment:
      REQUEST_ORIGIN: http://localhost:5000
    build: ../example-backend
    volumes:
      - ./example-backend/:/usr/src/app/backend
    container_name: web-backend
#    command: ["./server"]

  frontend:
#    image: node:16.20.2
    ports:
      - "5000:5000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    build: ../example-frontend
    volumes:
      - ./example-backend:/usr/src/app/frontend
    container_name: web-frontend
#    command: [ "serve", "-s", "-l", "5000", "build" ]

